# Generated by Django 4.2.11 on 2025-02-17 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribers",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="participaters",
            field=models.ManyToManyField(
                blank=True,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="participaters",
            ),
        ),
    ]
