# Generated by Django 4.2.11 on 2024-06-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                ("degree_id", models.AutoField(primary_key=True, serialize=False)),
                ("degree_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("dept_code", models.CharField(max_length=10, unique=True)),
                ("department_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sap_id", models.CharField(max_length=20, unique=True)),
                ("admission_year", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=20)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("registration_date", models.DateField()),
                ("registered_by", models.CharField(max_length=100)),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="xauth.degree",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_department",
                        to="xauth.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="degree",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="xauth.department"
            ),
        ),
    ]
