# Generated by Django 4.2.11 on 2024-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xauth", "0004_role_permission_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("parent", "Parent"),
                    ("alumni", "Alumni"),
                ],
                max_length=10,
            ),
        ),
    ]
