# Generated by Django 4.2.11 on 2024-06-10 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xauth", "0005_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permission",
            old_name="can_create",
            new_name="permitted",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="can_view",
        ),
    ]
