# Generated by Django 4.2.11 on 2024-06-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xauth", "0006_rename_can_create_permission_permitted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parents",
        ),
        migrations.AddField(
            model_name="student",
            name="parents",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xauth.parent",
            ),
        ),
    ]
