# Generated by Django 4.2.11 on 2024-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xauth", "0007_remove_student_parents_student_parents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parents",
        ),
        migrations.AddField(
            model_name="student",
            name="parents",
            field=models.ManyToManyField(to="xauth.parent"),
        ),
    ]
