# Generated by Django 4.2.11 on 2025-01-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xauth", "0009_degree_completion_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parents",
            field=models.ManyToManyField(blank=True, null=True, to="xauth.parent"),
        ),
    ]
